version: '3.4'

services:
  xkcdcomics:
    image: xkcdcomics_api
    build: ./
      # context: .
      # dockerfile: ./Dockerfile
    ports:
      - "1234:1234"
    networks:
      - xkcdcomics_network
networks:
  xkcdcomics_network: